name: Android CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  android-ci:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
        
      - name: Grant execute permission for gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
